
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 31 21:48:42 ART 2016
//----------------------------------------------------

package examples.while_ut1;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int NUMInt = 3;
  public static final int FUNCTION = 23;
  public static final int ASTERISK = 8;
  public static final int STR = 40;
  public static final int SLASH = 12;
  public static final int LESS_THAN_OR_EQUAL = 20;
  public static final int DOUBLE_AMPERSAND = 19;
  public static final int SEMICOLON = 14;
  public static final int DEFINED = 32;
  public static final int COMMA = 26;
  public static final int TBOOL = 33;
  public static final int RIGHT_PARENTHESIS = 7;
  public static final int QUESTION_MARK = 21;
  public static final int NUM = 2;
  public static final int IF = 38;
  public static final int LEFT_CURLY_BRACKET = 15;
  public static final int ID = 4;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int TRUE = 16;
  public static final int error = 1;
  public static final int TSTR = 36;
  public static final int VOID = 24;
  public static final int TINT = 34;
  public static final int COLON = 22;
  public static final int PLUS_SIGN = 11;
  public static final int ELSE = 37;
  public static final int SKIP = 28;
  public static final int WHILE = 29;
  public static final int THEN = 10;
  public static final int HYPHEN_MINUS = 13;
  public static final int TNUM = 35;
  public static final int EQUALS_SIGN = 17;
  public static final int EXCLAMATION_MARK = 5;
  public static final int FALSE = 9;
  public static final int RIGHT_CURLY_BRACKET = 18;
  public static final int PRINT = 30;
  public static final int LENGTH = 31;
  public static final int LEFT_PARENTHESIS = 6;
  public static final int DO = 27;
  public static final int DOUBLE_EQUALS_SIGN = 39;
}

